import stylisticPlugin from "@stylistic/eslint-plugin";
import typescriptPlugin from "@typescript-eslint/eslint-plugin";
import typescriptParser from "@typescript-eslint/parser";
import type {Linter} from "eslint";
import {importX} from "eslint-plugin-import-x";
import perfectionistPlugin from "eslint-plugin-perfectionist";
import unusedImportsPlugin from "eslint-plugin-unused-imports";
export default [
	{
		files: [`./**/*.js`, `./**/*.ts`],
		languageOptions: {
			parser: typescriptParser,
			parserOptions: {extraFileExtensions: [], project: `./tsconfig.json`},
			sourceType: `module`,
		},
	},
	{
		plugins: {
			"@stylistic": stylisticPlugin,
			/* @ts-expect-error */
			"@typescript-eslint": typescriptPlugin,
			"import-x": importX,
			"perfectionist": perfectionistPlugin,
			"unused-imports": unusedImportsPlugin,
		},
		rules: {
			"@stylistic/arrow-parens": [`warn`, `always`, {}],
			"@stylistic/line-comment-position": [`warn`, {position: `above`}],
			"@stylistic/lines-around-comment": [
				`warn`,
				{
					afterBlockComment: false,
					afterHashbangComment: false,
					afterLineComment: false,
					allowArrayEnd: true,
					allowArrayStart: true,
					allowBlockEnd: true,
					allowBlockStart: true,
					allowClassEnd: true,
					allowClassStart: true,
					allowEnumEnd: true,
					allowEnumStart: true,
					allowInterfaceEnd: true,
					allowInterfaceStart: true,
					allowModuleEnd: true,
					allowModuleStart: true,
					allowObjectEnd: true,
					allowObjectStart: true,
					allowTypeEnd: true,
					allowTypeStart: true,
					beforeBlockComment: false,
					beforeLineComment: false,
				},
			],
			"@stylistic/lines-between-class-members": [
				`warn`,
				`never`,
				{exceptAfterOverload: false, exceptAfterSingleLine: false},
			],
			"@stylistic/new-parens": [`warn`, `always`],
			"@stylistic/no-confusing-arrow": [
				`warn`,
				{allowParens: false, onlyOneSimpleParam: false},
			],
			"@stylistic/no-extra-parens": [
				`warn`,
				`all`,
				{
					conditionalAssign: true,
					enforceForFunctionPrototypeMethods: true,
					enforceForSequenceExpressions: true,
					ignoredNodes: [
						`ConditionalExpression`,
						`IntersectionType`,
						`SpreadElement[argument.type="ConditionalExpression"]`,
					],
					nestedBinaryExpressions: true,
					nestedConditionalExpressions: true,
					returnAssign: true,
					ternaryOperandBinaryExpressions: true,
				},
			],
			"@stylistic/no-extra-semi": [`warn`],
			"@stylistic/no-floating-decimal": [`warn`],
			"@stylistic/no-mixed-operators": [
				`warn`,
				{allowSamePrecedence: false, groups: []},
			],
			"@stylistic/no-multiple-empty-lines": [
				`warn`,
				{max: 0, maxBOF: 0, maxEOF: 0},
			],
			"@stylistic/padding-line-between-statements": [
				`warn`,
				{blankLine: `never`, next: `*`, prev: `*`},
			],
			"@stylistic/quotes": [
				`warn`,
				`backtick`,
				{
					allowTemplateLiterals: `always`,
					avoidEscape: false,
					ignoreStringLiterals: false,
				},
			],
			"@stylistic/semi": [
				`warn`,
				`always`,
				{omitLastInOneLineBlock: false, omitLastInOneLineClassBody: false},
			],
			"@typescript-eslint/adjacent-overload-signatures": [`warn`],
			"@typescript-eslint/array-type": [
				`warn`,
				{default: `array`, readonly: `array`},
			],
			"@typescript-eslint/await-thenable": [`warn`],
			"@typescript-eslint/class-literal-property-style": [`warn`, `fields`],
			"@typescript-eslint/class-methods-use-this": [
				`warn`,
				{
					enforceForClassFields: true,
					exceptMethods: [],
					ignoreClassesThatImplementAnInterface: true,
					ignoreOverrideMethods: true,
				},
			],
			"@typescript-eslint/consistent-indexed-object-style": [
				`warn`,
				`index-signature`,
			],
			"@typescript-eslint/consistent-type-assertions": [
				`warn`,
				{
					arrayLiteralTypeAssertions: `never`,
					assertionStyle: `as`,
					objectLiteralTypeAssertions: `never`,
				},
			],
			"@typescript-eslint/consistent-type-exports": [
				`warn`,
				{fixMixedExportsWithInlineTypeSpecifier: true},
			],
			"@typescript-eslint/consistent-type-imports": [
				`warn`,
				{
					disallowTypeAnnotations: true,
					fixStyle: `separate-type-imports`,
					prefer: `type-imports`,
				},
			],
			"@typescript-eslint/explicit-function-return-type": [
				`warn`,
				{
					allowConciseArrowFunctionExpressionsStartingWithVoid: false,
					allowDirectConstAssertionInArrowFunctions: false,
					allowedNames: [],
					allowExpressions: false,
					allowFunctionsWithoutTypeParameters: false,
					allowHigherOrderFunctions: false,
					allowIIFEs: false,
					allowTypedFunctionExpressions: true,
				},
			],
			"@typescript-eslint/explicit-member-accessibility": [
				`warn`,
				{accessibility: `explicit`, ignoredMethodNames: []},
			],
			"@typescript-eslint/explicit-module-boundary-types": [
				`warn`,
				{
					allowArgumentsExplicitlyTypedAsAny: false,
					allowDirectConstAssertionInArrowFunctions: false,
					allowedNames: [],
					allowHigherOrderFunctions: false,
					allowOverloadFunctions: false,
					allowTypedFunctionExpressions: false,
				},
			],
			"@typescript-eslint/init-declarations": [`warn`, `always`],
			"@typescript-eslint/member-ordering": [
				`warn`,
				{
					default: {
						memberTypes: [`static-field`, `constructor`, `instance-field`],
						order: `natural-case-insensitive`,
					},
				},
			],
			"@typescript-eslint/naming-convention": [
				`warn`,
				{
					format: [],
					modifiers: [],
					prefix: [],
					selector: [`objectLiteralMethod`, `objectLiteralProperty`],
					suffix: [],
					types: [],
				},
				{
					format: [`camelCase`],
					leadingUnderscore: `forbid`,
					modifiers: [],
					prefix: [],
					selector: [`default`],
					suffix: [],
					trailingUnderscore: `forbid`,
					types: [],
				},
				{
					format: [`camelCase`, `PascalCase`],
					leadingUnderscore: `forbid`,
					modifiers: [],
					prefix: [],
					selector: [`import`],
					suffix: [],
					trailingUnderscore: `forbid`,
					types: [],
				},
				{
					format: [`PascalCase`],
					leadingUnderscore: `forbid`,
					modifiers: [],
					prefix: [],
					selector: [`typeLike`],
					suffix: [],
					trailingUnderscore: `forbid`,
					types: [],
				},
			],
			"@typescript-eslint/no-array-constructor": [`warn`],
			"@typescript-eslint/no-array-delete": [`warn`],
			"@typescript-eslint/no-base-to-string": [
				`warn`,
				{checkUnknown: true, ignoredTypeNames: []},
			],
			"@typescript-eslint/no-confusing-void-expression": [
				`warn`,
				{
					ignoreArrowShorthand: false,
					ignoreVoidOperator: false,
					ignoreVoidReturningFunctions: false,
				},
			],
			"@typescript-eslint/no-deprecated": [`warn`, {allow: []}],
			"@typescript-eslint/no-dupe-class-members": [`warn`],
			"@typescript-eslint/no-duplicate-enum-values": [`warn`],
			"@typescript-eslint/no-duplicate-type-constituents": [
				`warn`,
				{ignoreIntersections: false, ignoreUnions: false},
			],
			"@typescript-eslint/no-dynamic-delete": [`warn`],
			"@typescript-eslint/no-empty-function": [
				`warn`,
				{allow: [`constructors`]},
			],
			"@typescript-eslint/no-empty-object-type": [
				`warn`,
				{allowInterfaces: `never`, allowObjectTypes: `never`},
			],
			"@typescript-eslint/no-explicit-any": [
				`warn`,
				{fixToUnknown: false, ignoreRestArgs: false},
			],
			"@typescript-eslint/no-extra-non-null-assertion": [`warn`],
			"@typescript-eslint/no-extraneous-class": [
				`warn`,
				{
					allowConstructorOnly: false,
					allowEmpty: false,
					allowStaticOnly: false,
					allowWithDecorator: false,
				},
			],
			"@typescript-eslint/no-floating-promises": [
				`warn`,
				{
					allowForKnownSafeCalls: [],
					allowForKnownSafePromises: [],
					checkThenables: false,
					ignoreIIFE: false,
					ignoreVoid: false,
				},
			],
			"@typescript-eslint/no-for-in-array": [`warn`],
			"@typescript-eslint/no-implied-eval": [`warn`],
			"@typescript-eslint/no-import-type-side-effects": [`warn`],
			"@typescript-eslint/no-invalid-this": [`warn`, {capIsConstructor: true}],
			"@typescript-eslint/no-invalid-void-type": [
				`warn`,
				{allowAsThisParameter: false, allowInGenericTypeArguments: true},
			],
			"@typescript-eslint/no-loop-func": [`warn`],
			"@typescript-eslint/no-meaningless-void-operator": [
				`warn`,
				{checkNever: true},
			],
			"@typescript-eslint/no-misused-new": [`warn`],
			"@typescript-eslint/no-misused-promises": [
				`warn`,
				{checksConditionals: true, checksSpreads: true, checksVoidReturn: true},
			],
			"@typescript-eslint/no-misused-spread": [`warn`, {allow: []}],
			"@typescript-eslint/no-mixed-enums": [`warn`],
			"@typescript-eslint/no-namespace": [
				`warn`,
				{allowDeclarations: false, allowDefinitionFiles: false},
			],
			"@typescript-eslint/no-non-null-asserted-nullish-coalescing": [`warn`],
			"@typescript-eslint/no-non-null-asserted-optional-chain": [`warn`],
			"@typescript-eslint/no-non-null-assertion": [`warn`],
			"@typescript-eslint/no-redeclare": [
				`warn`,
				{builtinGlobals: true, ignoreDeclarationMerge: false},
			],
			"@typescript-eslint/no-redundant-type-constituents": [`warn`],
			"@typescript-eslint/no-require-imports": [
				`warn`,
				{allow: [], allowAsImport: false},
			],
			"@typescript-eslint/no-restricted-types": [`warn`, {}],
			"@typescript-eslint/no-shadow": [
				`warn`,
				{
					allow: [],
					builtinGlobals: true,
					hoist: `all`,
					ignoreFunctionTypeParameterNameValueShadow: false,
					ignoreOnInitialization: true,
					ignoreTypeValueShadow: false,
				},
			],
			"@typescript-eslint/no-unnecessary-boolean-literal-compare": [
				`warn`,
				{
					allowComparingNullableBooleansToFalse: false,
					allowComparingNullableBooleansToTrue: false,
				},
			],
			"@typescript-eslint/no-unnecessary-condition": [
				`warn`,
				{allowConstantLoopConditions: `never`, checkTypePredicates: true},
			],
			"@typescript-eslint/no-unnecessary-parameter-property-assignment": [
				`warn`,
			],
			"@typescript-eslint/no-unnecessary-template-expression": [`warn`],
			"@typescript-eslint/no-unnecessary-type-assertion": [
				`warn`,
				{checkLiteralConstAssertions: false, typesToIgnore: []},
			],
			"@typescript-eslint/no-unnecessary-type-constraint": [`warn`],
			"@typescript-eslint/no-unnecessary-type-conversion": [`warn`],
			"@typescript-eslint/no-unnecessary-type-parameters": [`warn`],
			"@typescript-eslint/no-unsafe-argument": [`warn`],
			"@typescript-eslint/no-unsafe-assignment": [`warn`],
			"@typescript-eslint/no-unsafe-call": [`warn`],
			"@typescript-eslint/no-unsafe-declaration-merging": [`warn`],
			"@typescript-eslint/no-unsafe-enum-comparison": [`warn`],
			"@typescript-eslint/no-unsafe-function-type": [`warn`],
			"@typescript-eslint/no-unsafe-member-access": [
				`warn`,
				{allowOptionalChaining: false},
			],
			"@typescript-eslint/no-unsafe-return": [`warn`],
			"@typescript-eslint/no-unsafe-type-assertion": [`warn`],
			"@typescript-eslint/no-unsafe-unary-minus": [`warn`],
			"@typescript-eslint/no-unused-expressions": [
				`warn`,
				{
					allowShortCircuit: false,
					allowTaggedTemplates: false,
					allowTernary: false,
					ignoreDirectives: false,
				},
			],
			"@typescript-eslint/no-unused-private-class-members": [`warn`],
			"@typescript-eslint/no-unused-vars": [
				`warn`,
				{
					args: `none`,
					caughtErrors: `none`,
					enableAutofixRemoval: {imports: true},
					ignoreClassWithStaticInitBlock: false,
					ignoreRestSiblings: true,
					ignoreUsingDeclarations: false,
					vars: `all`,
				},
			],
			"@typescript-eslint/no-use-before-define": [
				`warn`,
				{
					allowNamedExports: false,
					classes: true,
					enums: true,
					functions: true,
					ignoreTypeReferences: false,
					typedefs: true,
					variables: true,
				},
			],
			"@typescript-eslint/no-useless-default-assignment": [`warn`, {}],
			"@typescript-eslint/no-useless-empty-export": [`warn`],
			"@typescript-eslint/no-wrapper-object-types": [`warn`],
			"@typescript-eslint/non-nullable-type-assertion-style": [`warn`],
			"@typescript-eslint/only-throw-error": [
				`warn`,
				{
					allow: [],
					allowRethrowing: false,
					allowThrowingAny: false,
					allowThrowingUnknown: false,
				},
			],
			"@typescript-eslint/parameter-properties": [
				`warn`,
				{allow: [], prefer: `class-property`},
			],
			"@typescript-eslint/prefer-as-const": [`warn`],
			"@typescript-eslint/prefer-enum-initializers": [`warn`],
			"@typescript-eslint/prefer-find": [`warn`],
			"@typescript-eslint/prefer-for-of": [`warn`],
			"@typescript-eslint/prefer-function-type": [`warn`],
			"@typescript-eslint/prefer-includes": [`warn`],
			"@typescript-eslint/prefer-literal-enum-member": [
				`warn`,
				{allowBitwiseExpressions: false},
			],
			"@typescript-eslint/prefer-namespace-keyword": [`warn`],
			"@typescript-eslint/prefer-promise-reject-errors": [
				`warn`,
				{
					allowEmptyReject: false,
					allowThrowingAny: false,
					allowThrowingUnknown: false,
				},
			],
			"@typescript-eslint/prefer-readonly": [
				`warn`,
				{onlyInlineLambdas: false},
			],
			"@typescript-eslint/prefer-reduce-type-parameter": [`warn`],
			"@typescript-eslint/prefer-return-this-type": [`warn`],
			"@typescript-eslint/prefer-string-starts-ends-with": [
				`warn`,
				{allowSingleElementEquality: `never`},
			],
			"@typescript-eslint/promise-function-async": [
				`warn`,
				{
					allowAny: true,
					allowedPromiseNames: [],
					checkArrowFunctions: true,
					checkFunctionDeclarations: true,
					checkFunctionExpressions: true,
					checkMethodDeclarations: true,
				},
			],
			"@typescript-eslint/related-getter-setter-pairs": [`warn`],
			"@typescript-eslint/require-array-sort-compare": [
				`warn`,
				{ignoreStringArrays: false},
			],
			"@typescript-eslint/restrict-plus-operands": [
				`warn`,
				{
					allowAny: false,
					allowBoolean: false,
					allowNullish: false,
					allowNumberAndString: false,
					allowRegExp: false,
					skipCompoundAssignments: false,
				},
			],
			"@typescript-eslint/restrict-template-expressions": [
				`warn`,
				{
					allow: [],
					allowAny: false,
					allowArray: false,
					allowBoolean: false,
					allowNever: true,
					allowNullish: false,
					allowNumber: false,
					allowRegExp: false,
				},
			],
			"@typescript-eslint/return-await": [`warn`, `always`],
			"@typescript-eslint/strict-boolean-expressions": [
				`warn`,
				{
					allowAny: false,
					allowNullableBoolean: false,
					allowNullableEnum: false,
					allowNullableNumber: false,
					allowNullableObject: false,
					allowNullableString: false,
					allowNumber: false,
					allowString: false,
				},
			],
			"@typescript-eslint/strict-void-return": [
				`warn`,
				{allowReturnAny: false},
			],
			"@typescript-eslint/unbound-method": [`warn`, {ignoreStatic: false}],
			"@typescript-eslint/unified-signatures": [
				`warn`,
				{
					ignoreDifferentlyNamedParameters: false,
					ignoreOverloadsWithDifferentJSDoc: false,
				},
			],
			"@typescript-eslint/use-unknown-in-catch-callback-variable": [`warn`],
			"arrow-body-style": [`warn`, `always`],
			"block-scoped-var": [`warn`],
			"camelcase": [
				`warn`,
				{
					allow: [],
					ignoreDestructuring: false,
					ignoreGlobals: false,
					ignoreImports: false,
					properties: `never`,
				},
			],
			"constructor-super": [`error`],
			"curly": [`warn`, `all`],
			"default-case-last": [`warn`],
			"eqeqeq": [`warn`, `always`, {null: `always`}],
			"for-direction": [`warn`],
			"func-names": [`warn`, `always`, {generators: `always`}],
			"func-style": [
				`warn`,
				`declaration`,
				{allowArrowFunctions: false, allowTypeAnnotation: false, overrides: {}},
			],
			"getter-return": [`warn`, {allowImplicit: false}],
			"grouped-accessor-pairs": [
				`warn`,
				`getBeforeSet`,
				{enforceForTSTypes: true},
			],
			"import-x/default": [`error`],
			"import-x/export": [`warn`],
			"import-x/exports-last": [`warn`],
			"import-x/first": [`warn`],
			"import-x/imports-first": [`warn`],
			"import-x/named": [`error`],
			"import-x/namespace": [`warn`, {allowComputed: false}],
			"import-x/no-absolute-path": [`warn`, {commonjs: true, esmodule: true}],
			"import-x/no-anonymous-default-export": [
				`warn`,
				{
					allowAnonymousClass: false,
					allowAnonymousFunction: false,
					allowArray: false,
					allowArrowFunction: false,
					allowCallExpression: false,
					allowLiteral: false,
					allowNew: false,
					allowObject: false,
				},
			],
			"import-x/no-commonjs": [`warn`, {allowRequire: false}],
			"import-x/no-cycle": [
				`error`,
				{
					allowUnsafeDynamicCyclicDependency: false,
					ignoreExternal: true,
					maxDepth: Infinity,
				},
			],
			"import-x/no-default-export": [`warn`],
			"import-x/no-deprecated": [`warn`],
			"import-x/no-duplicates": [
				`warn`,
				{considerQueryString: true, "prefer-inline": true},
			],
			"import-x/no-dynamic-require": [`warn`],
			"import-x/no-empty-named-blocks": [`warn`],
			"import-x/no-import-module-exports": [`warn`, {exceptions: []}],
			"import-x/no-internal-modules": [`warn`, {forbid: []}],
			"import-x/no-mutable-exports": [`warn`],
			"import-x/no-named-as-default": [`warn`],
			"import-x/no-named-as-default-member": [`warn`],
			"import-x/no-named-default": [`warn`],
			"import-x/no-relative-packages": [`warn`],
			"import-x/no-restricted-paths": [`error`],
			"import-x/no-self-import": [`warn`],
			"import-x/no-unassigned-import": [`warn`, {allow: []}],
			"import-x/no-useless-path-segments": [`warn`, {noUselessIndex: true}],
			"logical-assignment-operators": [`warn`, `never`],
			"max-classes-per-file": [`warn`, {ignoreExpressions: false, max: 1}],
			"new-cap": [
				`warn`,
				{
					capIsNew: true,
					capIsNewExceptions: [],
					newIsCap: false,
					newIsCapExceptions: [],
					properties: true,
				},
			],
			"no-async-promise-executor": [`warn`],
			"no-caller": [`error`],
			"no-case-declarations": [`warn`],
			"no-class-assign": [`warn`],
			"no-compare-neg-zero": [`warn`],
			"no-cond-assign": [`warn`, `always`],
			"no-const-assign": [`error`],
			"no-constant-binary-expression": [`warn`],
			"no-constant-condition": [`warn`, {checkLoops: `all`}],
			"no-constructor-return": [`warn`],
			"no-debugger": [`warn`],
			"no-delete-var": [`warn`],
			"no-dupe-args": [`warn`],
			"no-dupe-else-if": [`warn`],
			"no-dupe-keys": [`warn`],
			"no-duplicate-case": [`warn`],
			"no-duplicate-imports": [
				`warn`,
				{allowSeparateTypeImports: false, includeExports: true},
			],
			"no-empty": [`warn`, {allowEmptyCatch: false}],
			"no-empty-character-class": [`warn`],
			"no-empty-pattern": [`warn`, {allowObjectPatternsAsParameters: false}],
			"no-empty-static-block": [`warn`],
			"no-eq-null": [`warn`],
			"no-eval": [`warn`, {allowIndirect: false}],
			"no-ex-assign": [`warn`],
			"no-extend-native": [`warn`, {exceptions: []}],
			"no-extra-bind": [`warn`],
			"no-extra-boolean-cast": [`warn`, {enforceForInnerExpressions: true}],
			"no-extra-label": [`warn`],
			"no-func-assign": [`warn`],
			"no-global-assign": [`warn`, {exceptions: []}],
			"no-implicit-coercion": [
				`warn`,
				{
					allow: [],
					boolean: true,
					disallowTemplateShorthand: true,
					number: true,
					string: true,
				},
			],
			"no-implicit-globals": [`warn`, {lexicalBindings: false}],
			"no-import-assign": [`error`],
			"no-inner-declarations": [
				`warn`,
				`both`,
				{blockScopedFunctions: `disallow`},
			],
			"no-invalid-regexp": [`error`, {}],
			"no-irregular-whitespace": [
				`warn`,
				{
					skipComments: true,
					skipRegExps: true,
					skipStrings: true,
					skipTemplates: true,
				},
			],
			"no-label-var": [`warn`],
			"no-labels": [`warn`, {allowLoop: false, allowSwitch: false}],
			"no-lone-blocks": [`warn`],
			"no-loss-of-precision": [`warn`],
			"no-misleading-character-class": [`warn`, {allowEscape: false}],
			"no-multi-assign": [`warn`, {ignoreNonDeclaration: false}],
			"no-multi-str": [`warn`],
			"no-negated-condition": [`warn`],
			"no-nested-ternary": [`warn`],
			"no-new": [`warn`],
			"no-new-func": [`warn`],
			"no-new-native-nonconstructor": [`error`],
			"no-new-wrappers": [`warn`],
			"no-nonoctal-decimal-escape": [`warn`],
			"no-obj-calls": [`error`],
			"no-object-constructor": [`warn`],
			"no-octal": [`warn`],
			"no-octal-escape": [`warn`],
			"no-param-reassign": [`warn`, {props: false}],
			"no-plusplus": [`warn`, {allowForLoopAfterthoughts: false}],
			"no-promise-executor-return": [`warn`, {allowVoid: false}],
			"no-proto": [`warn`],
			"no-prototype-builtins": [`warn`],
			"no-restricted-imports": [`warn`],
			"no-restricted-syntax": [`warn`],
			"no-return-assign": [`warn`, `always`],
			"no-self-assign": [`warn`, {props: true}],
			"no-self-compare": [`warn`],
			"no-sequences": [`warn`, {allowInParentheses: false}],
			"no-setter-return": [`warn`],
			"no-shadow-restricted-names": [`warn`, {reportGlobalThis: true}],
			"no-sparse-arrays": [`warn`],
			"no-this-before-super": [`error`],
			"no-throw-literal": [`warn`],
			"no-unassigned-vars": [`warn`],
			"no-undef-init": [`warn`],
			"no-underscore-dangle": [
				`warn`,
				{
					allow: [],
					allowAfterSuper: false,
					allowAfterThis: false,
					allowAfterThisConstructor: false,
					allowFunctionParams: false,
					allowInArrayDestructuring: false,
					allowInObjectDestructuring: false,
					enforceInClassFields: true,
					enforceInMethodNames: true,
				},
			],
			"no-unexpected-multiline": [`warn`],
			"no-unmodified-loop-condition": [`warn`],
			"no-unneeded-ternary": [`warn`, {defaultAssignment: false}],
			"no-unreachable": [`warn`],
			"no-unsafe-finally": [`warn`],
			"no-unsafe-negation": [`warn`, {enforceForOrderingRelations: true}],
			"no-unsafe-optional-chaining": [
				`warn`,
				{disallowArithmeticOperators: true},
			],
			"no-unused-labels": [`warn`],
			"no-useless-assignment": [`warn`],
			"no-useless-backreference": [`warn`],
			"no-useless-call": [`warn`],
			"no-useless-catch": [`warn`],
			"no-useless-computed-key": [`warn`, {enforceForClassMembers: true}],
			"no-useless-concat": [`warn`],
			"no-useless-escape": [`warn`, {allowRegexCharacters: []}],
			"no-var": [`warn`],
			"no-void": [`warn`, {allowAsStatement: false}],
			"no-with": [`warn`],
			"object-shorthand": [`warn`, `never`],
			"one-var": [`warn`, `never`],
			"operator-assignment": [`warn`, `never`],
			"perfectionist/sort-array-includes": [
				`warn`,
				{
					customGroups: [],
					fallbackSort: {type: `unsorted`},
					groups: [],
					ignoreCase: true,
					newlinesBetween: 0,
					newlinesInside: 0,
					order: `asc`,
					partitionByComment: false,
					partitionByNewLine: false,
					specialCharacters: `keep`,
					type: `natural`,
				},
			],
			"perfectionist/sort-classes": [
				`warn`,
				{
					customGroups: [],
					fallbackSort: {type: `unsorted`},
					groups: [
						[`static-method`, `static-property`],
						[`constructor`],
						[`unknown`],
					],
					ignoreCase: true,
					newlinesBetween: 0,
					newlinesInside: 0,
					order: `asc`,
					partitionByComment: false,
					partitionByNewLine: false,
					specialCharacters: `keep`,
					type: `natural`,
				},
			],
			"perfectionist/sort-decorators": [
				`warn`,
				{
					customGroups: [],
					fallbackSort: {type: `unsorted`},
					groups: [],
					ignoreCase: true,
					newlinesBetween: 0,
					newlinesInside: 0,
					order: `asc`,
					partitionByComment: false,
					partitionByNewLine: false,
					sortOnAccessors: true,
					sortOnClasses: true,
					sortOnMethods: true,
					sortOnParameters: true,
					sortOnProperties: true,
					specialCharacters: `keep`,
					type: `natural`,
				},
			],
			"perfectionist/sort-enums": [
				`warn`,
				{
					customGroups: [],
					fallbackSort: {type: `unsorted`},
					groups: [],
					ignoreCase: true,
					newlinesBetween: 0,
					newlinesInside: 0,
					order: `asc`,
					partitionByComment: false,
					partitionByNewLine: false,
					specialCharacters: `keep`,
					type: `natural`,
				},
			],
			"perfectionist/sort-export-attributes": [
				`warn`,
				{
					customGroups: [],
					fallbackSort: {type: `unsorted`},
					groups: [],
					ignoreCase: true,
					newlinesBetween: 0,
					newlinesInside: 0,
					order: `asc`,
					partitionByComment: false,
					partitionByNewLine: false,
					specialCharacters: `keep`,
					type: `natural`,
				},
			],
			"perfectionist/sort-exports": [
				`warn`,
				{
					customGroups: [],
					fallbackSort: {type: `unsorted`},
					groups: [],
					ignoreCase: true,
					newlinesBetween: 0,
					newlinesInside: 0,
					order: `asc`,
					partitionByComment: false,
					partitionByNewLine: false,
					specialCharacters: `keep`,
					type: `natural`,
				},
			],
			"perfectionist/sort-heritage-clauses": [
				`warn`,
				{
					customGroups: [],
					fallbackSort: {type: `unsorted`},
					groups: [],
					ignoreCase: true,
					newlinesBetween: 0,
					newlinesInside: 0,
					order: `asc`,
					partitionByComment: false,
					partitionByNewLine: false,
					specialCharacters: `keep`,
					type: `natural`,
				},
			],
			"perfectionist/sort-import-attributes": [
				`warn`,
				{
					customGroups: [],
					fallbackSort: {type: `unsorted`},
					groups: [],
					ignoreCase: true,
					newlinesBetween: 0,
					newlinesInside: 0,
					order: `asc`,
					partitionByComment: false,
					partitionByNewLine: false,
					specialCharacters: `keep`,
					type: `natural`,
				},
			],
			"perfectionist/sort-imports": [
				`warn`,
				{
					customGroups: [],
					fallbackSort: {type: `unsorted`},
					groups: [],
					ignoreCase: true,
					newlinesBetween: 0,
					newlinesInside: 0,
					order: `asc`,
					partitionByComment: false,
					partitionByNewLine: false,
					sortBy: `path`,
					sortSideEffects: true,
					specialCharacters: `keep`,
					type: `natural`,
				},
			],
			"perfectionist/sort-interfaces": [
				`warn`,
				{
					customGroups: [],
					fallbackSort: {type: `unsorted`},
					groups: [],
					ignoreCase: true,
					newlinesBetween: 0,
					newlinesInside: 0,
					order: `asc`,
					partitionByComment: false,
					partitionByNewLine: false,
					sortBy: `name`,
					specialCharacters: `keep`,
					type: `natural`,
				},
			],
			"perfectionist/sort-intersection-types": [
				`warn`,
				{
					customGroups: [],
					fallbackSort: {type: `unsorted`},
					groups: [],
					ignoreCase: true,
					newlinesBetween: 0,
					newlinesInside: 0,
					order: `asc`,
					partitionByComment: false,
					partitionByNewLine: false,
					specialCharacters: `keep`,
					type: `natural`,
				},
			],
			"perfectionist/sort-maps": [
				`warn`,
				{
					customGroups: [],
					fallbackSort: {type: `unsorted`},
					groups: [],
					ignoreCase: true,
					newlinesBetween: 0,
					newlinesInside: 0,
					order: `asc`,
					partitionByComment: false,
					partitionByNewLine: false,
					specialCharacters: `keep`,
					type: `natural`,
				},
			],
			"perfectionist/sort-modules": [
				`warn`,
				{
					customGroups: [],
					fallbackSort: {type: `unsorted`},
					groups: [],
					ignoreCase: true,
					newlinesBetween: 0,
					newlinesInside: 0,
					order: `asc`,
					partitionByComment: false,
					partitionByNewLine: false,
					specialCharacters: `keep`,
					type: `natural`,
				},
			],
			"perfectionist/sort-named-exports": [
				`warn`,
				{
					customGroups: [],
					fallbackSort: {type: `unsorted`},
					groups: [],
					ignoreAlias: false,
					ignoreCase: true,
					newlinesBetween: 0,
					newlinesInside: 0,
					order: `asc`,
					partitionByComment: false,
					partitionByNewLine: false,
					specialCharacters: `keep`,
					type: `natural`,
				},
			],
			"perfectionist/sort-named-imports": [
				`warn`,
				{
					customGroups: [],
					fallbackSort: {type: `unsorted`},
					groups: [],
					ignoreAlias: false,
					ignoreCase: true,
					newlinesBetween: 0,
					newlinesInside: 0,
					order: `asc`,
					partitionByComment: false,
					partitionByNewLine: false,
					specialCharacters: `keep`,
					type: `natural`,
				},
			],
			"perfectionist/sort-object-types": [
				`warn`,
				{
					customGroups: [],
					fallbackSort: {type: `unsorted`},
					groups: [],
					ignoreCase: true,
					newlinesBetween: 0,
					newlinesInside: 0,
					order: `asc`,
					partitionByComment: false,
					partitionByNewLine: false,
					sortBy: `name`,
					specialCharacters: `keep`,
					type: `natural`,
				},
			],
			"perfectionist/sort-objects": [
				`warn`,
				{
					customGroups: [],
					fallbackSort: {type: `unsorted`},
					groups: [],
					ignoreCase: true,
					newlinesBetween: 0,
					newlinesInside: 0,
					order: `asc`,
					partitionByComment: false,
					partitionByNewLine: false,
					sortBy: `name`,
					specialCharacters: `keep`,
					type: `natural`,
				},
			],
			"perfectionist/sort-sets": [
				`warn`,
				{
					customGroups: [],
					fallbackSort: {type: `unsorted`},
					groups: [],
					ignoreCase: true,
					newlinesBetween: 0,
					newlinesInside: 0,
					order: `asc`,
					partitionByComment: false,
					partitionByNewLine: false,
					specialCharacters: `keep`,
					type: `natural`,
				},
			],
			"perfectionist/sort-switch-case": [
				`warn`,
				{
					fallbackSort: {type: `unsorted`},
					ignoreCase: true,
					order: `asc`,
					specialCharacters: `keep`,
					type: `natural`,
				},
			],
			"perfectionist/sort-union-types": [
				`warn`,
				{
					customGroups: [],
					fallbackSort: {type: `unsorted`},
					groups: [],
					ignoreCase: true,
					newlinesBetween: 0,
					newlinesInside: 0,
					order: `asc`,
					partitionByComment: false,
					partitionByNewLine: false,
					specialCharacters: `keep`,
					type: `natural`,
				},
			],
			"perfectionist/sort-variable-declarations": [
				`warn`,
				{
					customGroups: [],
					fallbackSort: {type: `unsorted`},
					groups: [],
					ignoreCase: true,
					newlinesBetween: 0,
					newlinesInside: 0,
					order: `asc`,
					partitionByComment: false,
					partitionByNewLine: false,
					specialCharacters: `keep`,
					type: `natural`,
				},
			],
			"prefer-const": [
				`warn`,
				{destructuring: `any`, ignoreReadBeforeAssign: false},
			],
			"prefer-exponentiation-operator": [`warn`],
			"prefer-named-capture-group": [`warn`],
			"prefer-numeric-literals": [`warn`],
			"prefer-object-has-own": [`warn`],
			"prefer-object-spread": [`warn`],
			"prefer-regex-literals": [`warn`, {disallowRedundantWrapping: true}],
			"prefer-rest-params": [`warn`],
			"prefer-spread": [`warn`],
			"prefer-template": [`warn`],
			"preserve-caught-error": [`warn`, {requireCatchParameter: true}],
			"radix": [`warn`],
			"require-atomic-updates": [`warn`, {allowProperties: false}],
			"require-unicode-regexp": [`warn`],
			"sort-imports": [
				`warn`,
				{
					allowSeparatedGroups: false,
					ignoreCase: true,
					ignoreDeclarationSort: true,
					ignoreMemberSort: false,
					memberSyntaxSortOrder: [`none`, `all`, `multiple`, `single`],
				},
			],
			"sort-keys": [
				`warn`,
				`asc`,
				{
					allowLineSeparatedGroups: false,
					caseSensitive: false,
					ignoreComputedKeys: false,
					minKeys: 2,
					natural: true,
				},
			],
			"sort-vars": [`warn`, {ignoreCase: true}],
			"strict": [`warn`, `never`],
			"symbol-description": [`warn`],
			"unicode-bom": [`warn`, `never`],
			"unused-imports/no-unused-imports": [`warn`],
			"use-isnan": [
				`warn`,
				{enforceForIndexOf: true, enforceForSwitchCase: true},
			],
			"valid-typeof": [`warn`, {requireStringLiterals: true}],
			"vars-on-top": [`warn`],
		},
	},
	{
		files: [`./**/!(index).ts`],
		rules: {
			"no-restricted-imports": [
				`warn`,
				{
					patterns: [
						{
							message: `Do not use an index file that the current file may be a part of.`,
							regex: `^(?:(?:\\.(?:\\.?)\\/)+)index\\.ts$`,
						},
						{
							message: `The import is too deep. Use a shallower index file.`,
							regex: `^(?:(?:\\.(?:\\.?)\\/)+)(?:(?:(?:(?:[^\\./])|(?:\\.[^\\.\\/])|(?:\\.\\.[^/]))(?:[^/]*)\\/){2,})index\\.ts$`,
						},
						{
							message: `Use an index file.`,
							regex: `^(?:(?:\\.(?:\\.?)\\/)+)(?:(?:(?:(?:[^\\./])|(?:\\.[^\\.\\/])|(?:\\.\\.[^/]))(?:[^/]*)\\/)+)(?!index\\.ts$)(?:[^/]*)$`,
						},
					],
				},
			],
		},
	},
	{
		files: [`./**/index.ts`],
		rules: {
			"no-restricted-imports": [
				`warn`,
				{
					patterns: [
						{
							message: `Do not import anything from a shallower path.`,
							regex: `^\\.\\.\\/(?:.+)$"`,
						},
						{
							message: `The import is too deep. Use a shallower index file.`,
							regex: `^\\.\\/(?:(?:(?:(?:[^\\./])|(?:\\.[^\\./])|(?:\\.\\.[^/]))(?:[^/]*)\\/){2,})index\\.ts$`,
						},
						{
							message: `Use an index file.`,
							regex: `^\\.\\/(?:(?:(?:(?:[^\\./])|(?:\\.[^\\./])|(?:\\.\\.[^/]))(?:[^/]*)\\/)+)(?!index\\.ts$)(?:[^/]*)$`,
						},
					],
				},
			],
		},
	},
	{
		files: [`./commitlint.config.ts`],
		rules: {"import-x/no-default-export": [`off`]},
	},
	{
		files: [`./eslint.config.ts`],
		rules: {"import-x/no-default-export": [`off`]},
	},
	{
		files: [`./prettier.config.ts`],
		rules: {"import-x/no-default-export": [`off`]},
	},
	{ignores: [`./.git`, `./node_modules`]},
] as const satisfies readonly Linter.Config[];
