services:
  wait-wait:
    build:
      args:
        DEBIAN__DOCKER_IMAGE__TAG__DATE: "20251208"
        NODE_JS__VERSION: "24.14.0"
      context: "."
      dockerfile: "Dockerfile"
    environment: {}
    volumes:
      - consistency: "consistent"
        read_only: false
        source: ".."
        target: "/home/developer/wait-wait"
        type: "bind"
      - consistency: "consistent"
        read_only: false
        source: "./.bashrc"
        target: "/home/developer/.bashrc"
        type: "bind"
