env:
  NODEJS_VERSION: "24.14.0"
jobs:
  commitlint_check:
    name: "commitlint check"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v6.0.2"
      - name: "Setup Node.js"
        uses: "actions/setup-node@v6.3.0"
        with:
          cache: "npm"
          node-version: "${{env.NODEJS_VERSION}}"
      - name: "Install the dependencies"
        run: "npm ci"
      - name: "Run the commitlint check"
        run: |
          npm run commitlint:check:range -- --from=${{github.event.before}} --to=${{github.sha}}
  eslint_check:
    name: "ESLint check"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v6.0.2"
      - name: "Setup Node.js"
        uses: "actions/setup-node@v6.3.0"
        with:
          cache: "npm"
          node-version: "${{env.NODEJS_VERSION}}"
      - name: "Install the dependencies"
        run: "npm ci"
      - name: "Run the ESLint check"
        run: |
          npm run eslint:check
  prettier_check:
    name: "Prettier check"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v6.0.2"
      - name: "Setup Node.js"
        uses: "actions/setup-node@v6.3.0"
        with:
          cache: "npm"
          node-version: "${{env.NODEJS_VERSION}}"
      - name: "Install the dependencies"
        run: "npm ci"
      - name: "Run the Prettier check"
        run: |
          npm run prettier:check
  test_check:
    name: "Test check"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v6.0.2"
      - name: "Setup Node.js"
        uses: "actions/setup-node@v6.3.0"
        with:
          cache: "npm"
          node-version: "${{env.NODEJS_VERSION}}"
      - name: "Install the dependencies"
        run: "npm ci"
      - name: "Run the test check"
        run: |
          npm run test:check
  typescript_check:
    name: "TypeScript check"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v6.0.2"
      - name: "Setup Node.js"
        uses: "actions/setup-node@v6.3.0"
        with:
          cache: "npm"
          node-version: "${{env.NODEJS_VERSION}}"
      - name: "Install the dependencies"
        run: "npm ci"
      - name: "Run the TypeScript check"
        run: |
          npm run typescript:check
name: "Continuous integration"
on:
  pull_request:
  push:
